### DISCUSSION TITLE
.Net Core 3.1 builds fails because sdk was removed from github images

### DISCUSSION THREAD

**Discussion by inforithmics** [vvvv/SVG#1072] [General]
1. Solution use a newer .net sdk/runtime to run and test for example .NET 6

2. Install the .NET SDK 3.1 in the Github action
```
 - name: Setup .NET 3.1 SDK
         uses: actions/setup-dotnet@v3
      with:
         dotnet-version: |
           3.1.x
         include-prerelease: false
```
